#!/usr/bin/env python
"""
sample_test

autogenerated sample test for sovereign_risk_disaster
"""
import unittest
import sovereign_risk_disaster

class SampleTest(unittest.TestCase):
    """placeholder for real tests"""
    def test_sample(self):
        self.failUnless(True)



if __name__ == '__main__':
    unittest.main()